### ISSUE TITLE
proposal: Campus and Academic Scheduling

### ISSUE THREAD

**Issue by thailandmatt** [byuoitav/uapi-translator#13]
**Proposal**: Campus and Academic Scheduling

**Goal**: Provide campus and academic scheduling systems with relevant and descriptive information about technology within each room.

**Scope**: “Implementation of the sync would require AV services to expose an API so the academic scheduling system could pull information from the AV services database.  When the AV database changes, an event pushed to the University Event Bus would trigger the synchronization process from the scheduling system.  The scheduling system is maintained by another group within OIT; we would work closely with Ryan Cater (the Product Manager) to coordinate the implementation of the synchronization process.”

**Implementation Proposal**:
I propose that we either add a field `external-description` or re-purpose the field `description` to the `device` document for this purpose.

This field would be added to the `device-type` document as well, and would provide the default for new devices that are added to a room.

A similar field would be added to the `room` document.

These fields would be filled out to be human readable upon install (after an initial push to populate the existing rooms).

The API endpoint would aggregate these fields for a room and return an array of strings as the result of the API call.  Documents missing the field or with the “external-description” field blank would not be included.

Examples:
**BNSN-W006**
 
![image](https://user-images.githubusercontent.com/31248374/78690962-53e2af00-78b5-11ea-8068-af979e80f804.png)
 
![image](https://user-images.githubusercontent.com/31248374/78690977-57763600-78b5-11ea-927f-d56189e5d697.png)
 
![image](https://user-images.githubusercontent.com/31248374/78690989-59d89000-78b5-11ea-929e-bd984854f0c0.png)
 
![image](https://user-images.githubusercontent.com/31248374/78690996-5ba25380-78b5-11ea-9de7-e9f2316d1865.png)
 
![image](https://user-images.githubusercontent.com/31248374/78691002-60670780-78b5-11ea-9730-4bcd7c25af78.png)

![image](https://user-images.githubusercontent.com/31248374/78691015-63fa8e80-78b5-11ea-813b-172200ce3de0.png)
 
API result:
```{  
room: “BNSN-W006”,  
items: [  
“Teaching Podium”,  
“Pull-down projection screen”,  
“On-wall Media Speakers”,  
“1 Projector (Sony PHZ10)”,  
“1 HDMI Cable in podium”,  
“1 HDMI Jack in podium”,  
“1 TEC PC w/ keyboard and mouse in podium”,  
“1 VIA Wireless Presentation System”  
]  
}
```

**EB-321:**
EB-321-D1 description = “Projector (Sony Z66)”
EB-321-D2 description = “Projector (Sony Z66)”
EB-321-D3 description = “Flat Panel Display (Sony 55\”)”
EB-321-D4 description = “Flat Panel Display (Sony 55\”)”
EB-321-D5 description = “Flat Panel Display (Sony 55\”)”

EB-321-HDMI1 description = “HDMI Jack”
EB-321-MIC1 description = “Wireless Mic”
EB-321-MICJK1 description = “Wired Mic Jack”
EB-321-PC1 description = “TEC PC w/ Wireless keyboard and mouse”

EB-321-VIA1 description = “VIA Wireless Presentation System”
EB-321-VIA2 description = “VIA Wireless Presentation System”

EB-321 description = “TEC PC has 3 extended displays, which show on the 3 FPDs (confidence monitors)\nAll 3 PC Screens, HDMI Inputs and VIA Inputs can be projected on the screens independently\n2 Motorized Projection Screens\nIn-ceiling speakers”

API result:
```
{
room: “EB-321”,
items: [
“TEC PC has 3 extended displays, which show on the 3 FPDs (confidence monitors)”,
“All 3 PC Screens, HDMI Inputs and VIA Inputs can be projected on the screens independently”,
“2 Motorized Projection Screens”,
“In-ceiling speakers”,
“2 Projector (Sony Z66)”,
“3 Flat Panel Display (Sony 55\”)”,
“1 HDMI Jack”,
“1 Wireless Mic”,
“1 Wired Mic Jack”,
“1 TEC PC w/ keyboard and mouse in podium”,
“2 VIA Wireless Presentation System”
]
}
```

**CTB-410:**
CTB-410-D1 description = “Projector (Sony PHZ65)”
CTB-410-D2 – D8 description = “Flat Panel Display (Sony 75\”)”

CTB-410-HDMI1 description = “Teaching station HDMI Jack”
CTB-410-HDMI2 – HDMI8 description = “Local station HDMI Jack”

CTB-410-PC1 description = “TEC PC w/ wireless keyboard and mouse”
CTB-410-VIA1 description = “Teaching station VIA Wireless Presentation System”
CTB-410-VIA2 – VIA8 description = “Local station VIA Wireless Presentation System”

CTB-410 = “Active learning technology space\nSharing content enabled from any station to any/all other stations\nMotorized Projection Screen”

API result:
```
{
room: “CTB-410”,
items: [
“Active learning technology space”,
“Sharing content enabled from any station to any/all other stations”,
“Motorized Projection Screen”,
“1 Projector (Sony Z65)”,
“7 Flat Panel Display (Sony 75\”)”,
“1 Teaching station HDMI Jack”,
“7 Local station HDMI Jack”,
“1 TEC PC w/ keyboard and mouse in podium”,
“1 Teaching station VIA Wireless Presentation System”,
“7 Local station VIA Wireless Presentation System”
]
}

```

**Comment by bwinterton** [comment]
I have a couple of thoughts for this proposal and things I would like to propose changes to over the initial proposal. These thoughts are all centered around a couple of goals:
* Draw a line between "Room Description" and "Items that are in the room"
* Produce a more adaptable API that is easier to parse and serves a more general audience. 
* Minimize duplicated data

### API Changes

I want to start with the API response first as part of an API First design model: 
* BNSN-W006:
```json
{
    "av_room_id": "BNSN-W006",
    "room_number": "W006",
    "building_abbreviation": "BNSN",
    "av_room_description": "Basic teaching space with a teaching podium, pulldown projection screen, and On-Wall Media Speakers.",
    "av_resources": [
        {
            "quantity": 1,
            "resource": "Projector (Sony PHZ10)",
            "locations": []
        },
        {
            "quantity": 1,
            "resource": "HDMI Cable",
            "locations": [
                "Podium"
            ]
        },
        {
            "quantity": 1,
            "resource": "HDMI Jack",
            "locations": [
                "Podium"
            ]
        },
        {
            "quantity": 1,
            "resource": "TEC PC with keyboard and mouse",
            "locations": [
                "Podium"
            ]
        },
        {
            "quantity": 1,
            "resource": "VIA Wireless Presentation System",
            "locations": []
        }
    ]
}
```
* EB 321 Response:
```json
{
    "av_room_id": "EB-321",
    "room_number": "321",
    "building_abbreviation": "EB",
    "av_room_description": "A teaching space with a TEC PC which includes three extended displays, which can show on the 3 confidence monitors. All 3 PC screens, HDMI inputs, and VIA inputs can be projected on the screens independently. The room also has two motorized projector screens and in-ceiling speakers.",
    "av_resources": [
        {
            "quantity": 2,
            "resource": "Projector (Sony Z66)",
            "locations": []
        },
        {
            "quantity": 3,
            "resource": "Flat Panel Display (Sony 55)",
            "locations": []
        },
        {
            "quantity": 1,
            "resource": "HDMI Jack",
            "locations": []
        },
        {
            "quantity": 1,
            "resource": "Wireless Mic",
            "locations": []
        },
        {
            "quantity": 1,
            "resource": "Wired Mic Jack",
            "locations": []
        },
        {
            "quantity": 1,
            "resource": "TEC PC with keyboard and mouse",
            "locations": [
                "Podium"
            ]
        },
        {
            "quantity": 2,
            "resource": "VIA Wireless Presentation System",
            "locations": []
        }
    ]
}
```

* CTB 410 Response:
```json
{
    "av_room_id": "CTB-410",
    "room_number": "410",
    "building_abbreviation": "CTB",
    "av_room_description": "Active learning technology space. Sharing content is allowed from any station to any/all other stations. The room also has a motorized projection screen.",
    "av_resources": [
        {
            "quantity": 1,
            "resource": "Projector (Sony Z65)",
            "locations": []
        },
        {
            "quantity": 7,
            "resource": "Flat Panel Display (Sony 75)",
            "locations": []
        },
        {
            "quantity": 8,
            "resource": "HDMI Jack",
            "locations": [
                "Teaching Station",
                "Station 1",
                "Station 2",
                "Station 3",
                "Station 4",
                "Station 5",
                "Station 6",
                "Station 7"
            ]
        },
        {
            "quantity": 1,
            "resource": "TEC PC with keyboard and mouse",
            "locations": [
                "In Podium"
            ]
        },
        {
            "quantity": 8,
            "resource": "VIA Wireless Presentation System",
            "locations": [
                "Teaching Station",
                "Station 1",
                "Station 2",
                "Station 3",
                "Station 4",
                "Station 5",
                "Station 6",
                "Station 7"
            ]
        }
    ]
}
```

The changes to the API responses above give us a couple of advantages:
* The API response is more easily parsed to fit various need
 * By having the quantity, resource, and locations separated it allows various clients to pull the information they need without having to parse through a plain text string
* The item names fall more in line with UAPI guidelines and will fit easily into the data governance process
* The response separates out the description of the room and the type of space it is from the actual items found in the room
 * This again allows more flexibility for clients to see what they need to see and ignore what they don't

Note: `resource`, `quantity`, and `location` property names are subject to change based on the data governance requirements. I am double checking on this. 

### Database Changes

In order to achieve the given API responses, I propose the following changes to our database structure:
* Rooms:
  * Remove `description` property
  * Add a field `description` under `tags` which will contain the information which will populate the `av_room_description` field in the API
* Device Types:
  * Remove `description` and `display_name` properties
  * Change `tags` property to an object
  * Add a `description` tag which will serve as a backup for populating the field `resource` in the `av_resources` objects
    * Note: The thought process here is that an individual device _may_ define it's own "resource name" or it may fallback on the name defined on the type. This will save us a _lot_ of time and duplicated data entry
* Devices:
  * Remove `display_name` and `description` properties
  * Change `type._id` to `typeID`
  * Change `tags` to object
  * Add a `location` tag which will be set to the human-readable location of that device in the room. This is used to populate the `locations` array
    * Note: This tag is not required by the API
  * Add a `description` tag which is set to a human-readable description of the device which will be used to populate the `resource` property of the `av_resources` objects.
    * Note: This tag is not required by the API, if not set on the device, the API will fallback to the `description` tag on the device type

Note: These changes merge in some of the changes discussed in byuoitav/av-control-api#27

This will result in database entries as follows:

#### Rooms
* BNSN-W006
```json
{
  "_id": "BNSN-W006",
  "_rev": "1-5e3f625b67c64966b4c7b03255903b9e",
  "name": "BNSN-W006",
  "configuration": {
    "_id": "Tiered Switcher"
  },
  "designation": "production",
  "tags": {
    "description": "Basic teaching space with a teaching podium, pulldown projection screen, and On-Wall Media Speakers."
  } 
}
```

#### Device Types
* via-connect-pro
```json
{
  "_id": "via-connect-pro",
  "input": true,
  "output": true,
  "source": true,
  "roles": [...],
  "commands": [...],
  "tags": {
    "description": "VIA Wireless Presentation System"
  }
}
```
* Sony PHZ10
```json
{
  "_id": "Sony PHZ10",
  "output": true,
  "destination": true,
  "roles": [...],
  "commands": [...],
  "tags": {
    "description": "Projector (Sony PHZ10)"
  }
}
```

#### Devices

* BNSN-W006-HDMI1
```json
{
  "_id": "BNSN-W006-HDMI1",
  "name": "HDMI1",
  "address": "0.0.0.0",
  "typeID": "non-controllable",
  "roles": [...],
  "ports": [...],
  "tags": {
    "description": "HDMI Cable",
    "location": "Podium"
  }
}
```

* BNSN-W006-HDMI2
```json
{
  "_id": "BNSN-W006-HDMI2",
  "name": "HDMI2",
  "address": "0.0.0.0",
  "typeID": "non-controllable",
  "roles": [...],
  "ports": [...],
  "tags": {
    "description": "HDMI Jack",
    "location": "Podium"
  }
}
```

* BNSN-W006-VIA1
```json
{
  "_id": "BNSN-W006-VIA1",
  "_rev": "1-12bf7cf9b1f7754dde127dd905bee69d",
  "name": "VIA1",
  "address": "BNSN-W006-VIA1.byu.edu",
  "typeID": "via-connect-pro",
  "roles": [...],
  "ports": [...]
}
```

### Summary

Overall, these changes should help us accomplish our goals of providing service to users like Campus Scheduling while also achieving the following goals:
* Simplify database structures
* Reduce effort on installers, engineers, etc. for new devices/rooms/etc.
* Reduce initial population effort in the database
* Reduce duplication of data
* Produce an API that is more flexible and allows for various consumption patterns
* Produce an API that more closely aligns with the UAPI standard, making transition easier
